CREATE TABLE [00-Ticket Distribution Table] (
  [ID] DOUBLE ,
  [Status] VARCHAR (255),
  [Delivery #] DOUBLE ,
  [Date] DATETIME ,
  [Location Name] VARCHAR (255),
  [Legal Name] VARCHAR (255),
  [Charity Association] VARCHAR (255),
  [Sales Rep] VARCHAR (255),
  [Marketing Rep] VARCHAR (255),
  [Rep Commission] VARCHAR (255),
  [Serial #] VARCHAR (255),
  [Supplier] VARCHAR (255),
  [Game Name] VARCHAR (255),
  [Ticket Count] DOUBLE ,
  [Ticket Value] CURRENCY ,
  [Total Revenue] CURRENCY ,
  [Prizes Paid] CURRENCY ,
  [Profit] CURRENCY ,
  [Rent] CURRENCY ,
  [Billing Style] VARCHAR (255),
  [Total Billable] CURRENCY ,
  [Ticket Supply Cost] CURRENCY ,
  [SMAC Service Fee] CURRENCY ,
  [SMAC Admin Fee] CURRENCY ,
  [Location Check #] VARCHAR (255),
  [Reimbursement Check #] DOUBLE ,
  [Envelope #] DOUBLE ,
  [Reimbursement Sent] DATETIME 
)
