CREATE TABLE [00-Ticket Inventory Table] (
  [ID] DOUBLE ,
  [Date Acquired] DATETIME ,
  [Date Distributed] VARCHAR (255),
  [Sold Same Month] VARCHAR (255),
  [Status] VARCHAR (255),
  [Purchaser] VARCHAR (255),
  [Supplier] VARCHAR (255),
  [Invoice #] VARCHAR (255),
  [Sales Order #] VARCHAR (255),
  [Serial #] VARCHAR (255),
  [Item #] VARCHAR (255),
  [Game Name] VARCHAR (255),
  [Game Price] CURRENCY ,
  [Ticket Count] DOUBLE ,
  [Ticket Value] CURRENCY ,
  [Revenue] CURRENCY ,
  [Ideal Profit] CURRENCY ,
  [Prizes Paid] CURRENCY ,
  [Location Rent] CURRENCY ,
  [Last Sale] CURRENCY ,
  [Initial Supply Stock Owner] VARCHAR (255),
  [Transfer Date] VARCHAR (255),
  [Charity Distributed For] VARCHAR (255),
  [SMAC-D Sale Invoice #] VARCHAR (255),
  [Sale Date] VARCHAR (255),
  [New Supply Stock Owner] VARCHAR (255)
)
