CREATE TABLE [Collections] (
  [Id] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [CollectionStubId] LONG ,
  [EquipmentId] LONG ,
  [TransactionType] VARCHAR (255),
  [Split] DOUBLE ,
  [Amount] CURRENCY ,
  [CustomFee] CURRENCY ,
  [Notes] VARCHAR (255),
  [ServicePercentage] DOUBLE ,
  [ServiceFee] CURRENCY ,
  [ServiceFeeAmount] DOUBLE ,
  [CreditCardFeeAmount] DOUBLE ,
  [CreditCardPercentage] DOUBLE ,
  [CreditCardFee] CURRENCY ,
  [LocationPercentage] DOUBLE ,
  [LocationFee] CURRENCY ,
  [LocationFeeAmount] CURRENCY ,
  [IsApproved] BIT ,
  [CashAfterSplitFees] CURRENCY ,
  [ApplyLocationFee] BIT ,
  [UpdatedAt] DATETIME ,
  [UpdatedBy] VARCHAR (255)
)
