CREATE TABLE [Collections-Splitted] (
  [Id] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [CollectionStubId] LONG ,
  [CollectionId] LONG ,
  [CollectionDate] DATETIME ,
  [EmployeeId] LONG ,
  [LocationId] LONG ,
  [EquipmentId] LONG ,
  [TransactionType] VARCHAR (255),
  [Split] DOUBLE ,
  [Amount] CURRENCY ,
  [CustomFee] CURRENCY ,
  [Notes] VARCHAR (255),
  [SplittedAmount] DOUBLE ,
  [ServicePercentage] DOUBLE ,
  [ServiceFee] CURRENCY ,
  [ServiceFeeAmount] CURRENCY ,
  [CreditCardPercentage] DOUBLE ,
  [CreditCardFee] CURRENCY ,
  [CreditCardFeeAmount] CURRENCY ,
  [LocationPercentage] DOUBLE ,
  [LocationFee] CURRENCY ,
  [IsApproved] BIT ,
  [LocationFeeAmount] CURRENCY ,
  [UpdatedAt] DATETIME ,
  [UpdatedBy] VARCHAR (255)
)
