CREATE TABLE [Employees1] (
  [Id] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [FirstName] VARCHAR (255),
  [LastName] VARCHAR (255),
  [FullName] VARCHAR (243),
  [Division] LONG ,
  [Notes] VARCHAR (255),
  [HomePhone] VARCHAR (255),
  [BusinessPhone] VARCHAR (255),
  [Address] VARCHAR (255),
  [City] VARCHAR (255),
  [State] VARCHAR (255),
  [Zip] VARCHAR (255),
  [E-mailAddress] VARCHAR (255),
  [Date of Birth] DATETIME ,
  [Mobile] VARCHAR (255),
  [Fax] VARCHAR (255),
  [PIN (Pager)] VARCHAR (255),
  [Company] VARCHAR (255),
  [PassNumber] VARCHAR (255),
  [Country] VARCHAR (255),
  [WebPage] VARCHAR (255),
  [Attachments] VARCHAR ,
  [BusinessRole] LONG ,
  [ManagerId] LONG ,
  [UserType] LONG ,
  [UserName] VARCHAR (255),
  [Password] VARCHAR (255),
  [Comments] LONGTEXT ,
  [TimeOffLeft] LONG ,
  [IsActive] BIT ,
  [UpdatedAt] DATETIME ,
  [UpdatedBy] VARCHAR (255),
  [ADPFullName] VARCHAR (243),
  [SalesRep] BIT 
)
