CREATE TABLE [Locations] (
  [id] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [BusinessPartnerId] LONG ,
  [LocationName] VARCHAR (255),
  [LastName] VARCHAR (50),
  [FirstName] VARCHAR (50),
  [E-mail] VARCHAR (50),
  [JobTitle] VARCHAR (50),
  [BusinessPhone] VARCHAR (25),
  [HomePhone] VARCHAR (25),
  [MobilePhone] VARCHAR (25),
  [FaxNumber] VARCHAR (25),
  [Address] LONGTEXT ,
  [City] VARCHAR (50),
  [State] VARCHAR (50),
  [ZIP] VARCHAR (15),
  [Country] VARCHAR (50),
  [WebPage] LONGTEXT ,
  [Notes] LONGTEXT ,
  [Attachments] VARCHAR ,
  [IsActive] BIT ,
  [PayeeName] VARCHAR (255),
  [ContractExpirationDate] DATETIME ,
  [SalesRepId] LONG ,
  [MarketingRepId] LONG ,
  [Status] VARCHAR (255),
  [UpdatedAt] DATETIME ,
  [UpdatedBy] VARCHAR (255)
)
