CREATE TABLE [PayrollSplittedEntries] (
  [id] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [PayrollId] LONG ,
  [CheckDate] DATETIME ,
  [PayPeriodStart] DATETIME ,
  [PayPeriodEnd] DATETIME ,
  [EmployeeId] LONG ,
  [DivisionId] LONG ,
  [Split] DOUBLE ,
  [Total-GrossPay] CURRENCY ,
  [Total-NetPay] CURRENCY ,
  [Total-ER-SS] CURRENCY ,
  [Total-ER-MC] CURRENCY ,
  [Total-FUTA] CURRENCY ,
  [Total-SUTA] CURRENCY ,
  [Calc-GrossPay] DOUBLE ,
  [Calc-ER-SS] DOUBLE ,
  [Calc-ER-MC] DOUBLE ,
  [Calc-SUTA] DOUBLE ,
  [Calc-FUTA] DOUBLE ,
  [Calc-TotalTax] DOUBLE ,
  [Calc-TotalLiability] DOUBLE ,
  [CalcNetPay] DOUBLE ,
  [UpdatedAt] DATETIME ,
  [UpdatedBy] VARCHAR (255)
)
