CREATE TABLE [PayrollEntries] (
  [id] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [CheckDate] DATETIME ,
  [PayPeriodStart] DATETIME ,
  [PayPeriodEnd] DATETIME ,
  [EmployeeId] LONG ,
  [SSN] VARCHAR (255),
  [GrossPay] CURRENCY ,
  [FWT] CURRENCY ,
  [SocSec] CURRENCY ,
  [Medicaid] CURRENCY ,
  [Ohio] CURRENCY ,
  [Cleveland] CURRENCY ,
  [TotalTax] CURRENCY ,
  [NetPay] CURRENCY ,
  [FED_SOCSEC_ER] CURRENCY ,
  [FED_MEDCARE_ER] CURRENCY ,
  [FED_FUTA] CURRENCY ,
  [SUTA] CURRENCY ,
  [TotalEmployerTax] CURRENCY ,
  [FileName] VARCHAR (255),
  [PayCycle] VARCHAR (255),
  [UpdatedAt] DATETIME ,
  [UpdatedBy] VARCHAR (255)
)
