CREATE TABLE [TicketDistribution] (
  [Id] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Status] VARCHAR (255),
  [DeliveryNumber] DOUBLE ,
  [DistributionDate] DATETIME ,
  [CharityId] LONG ,
  [LocationId] LONG ,
  [SalesRepId] LONG ,
  [MarketingRepId] LONG ,
  [RepCommission] CURRENCY ,
  [SerialNumber] VARCHAR (255),
  [SupplierId] LONG ,
  [GameName] LONG ,
  [TicketCount] DOUBLE ,
  [TicketValue] CURRENCY ,
  [TotalRevenue] CURRENCY ,
  [PrizesPaid] CURRENCY ,
  [Profit] CURRENCY ,
  [Rent] CURRENCY ,
  [BillingStyle] VARCHAR (255),
  [TotalBillable] CURRENCY ,
  [TicketSupplyCost] CURRENCY ,
  [SMACServiceFee] CURRENCY ,
  [SMACAdminFee] CURRENCY ,
  [LocationCheckNumber] VARCHAR (255),
  [ReimbursementCheckNumber] DOUBLE ,
  [EnvelopeNumber] DOUBLE ,
  [ReimbursementSent] DATETIME ,
  [CharityInvoiceNumber] VARCHAR (255),
  [UpdatedAt] DATETIME ,
  [UpdatedBy] VARCHAR (255)
)
